reminder/reminder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('todo.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

reminder/todo/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('', index, name='index'),

    path('tasks/', TaskListView.as_view(), name='tasks'),

    path('expired_tasks/', expired_tasks, name="expired_tasks"),

    path('unexpired_tasks/', unexpired_tasks, name="unexpired_tasks"),

    path('last_tasks/', last_tasks, name="last_tasks"),

    path('categories/', CategoriesListView.as_view(), name='categories'),

    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),

    path('empty_categories/', empty_categories, name='empty_categories'),

    path('popular_categories/', popular_categories, name='popular_categories'),

    path('tasks/<int:pk>/', TaskDetailView.as_view(), name='task_detail'),

    path('add_category/',add_category, name='add_category')
]

reminder/todo/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=100)
    
    def __str__(self) -> str:
        return self.name

    class Meta():
        verbose_name_plural = "Categories"

class Task(models.Model):
    #  defining the choices and names for each choice inside the model class keeps all 
    # of that information with the class that uses it, and helps reference the choices
    PRIORITY_CHOICES = [(3,"Low"), (2,"Medium"), (1,"High")]
    categories = models.ManyToManyField(Category,)
    title = models.CharField(max_length=30)
    description = models.TextField()
    priority = models.IntegerField(choices=PRIORITY_CHOICES)
    schedule = models.DateTimeField()
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title

reminder/todo/views.py
from django.db.models import query
from django.http.response import JsonResponse
from django.shortcuts import render
from django.utils.regex_helper import Choice
from django.views.generic import TemplateView, DetailView, ListView, View
from .models import *
from django.utils import timezone
from datetime import datetime
from django.db.models import Count


def index(request):
    if request.method == "POST" and request.is_ajax():
        # print(dict(request.POST.items()))
        title = request.POST.get('title')
        description = request.POST.get('description')
        priority = request.POST.get('priority')
        categories = request.POST.getlist('categories[]')
        schedule =  datetime.strptime(request.POST.get('schedule'), '%Y-%m-%dT%H:%M')
        task = Task.objects.create(title=title, description=description, priority=priority, schedule=schedule)
        for category in categories:
            category_obj = Category.objects.get(name=category)
            task.categories.add(category_obj)
        # print(task.categories.all())
        return JsonResponse({})
    return render(request, "todo/index.html", {"categories":Category.objects.all()})


def add_category(request):
    if request.method == "POST" and request.is_ajax():
        name = request.POST.get('name')
        description = request.POST.get('description')
        if Category.objects.filter(name__iexact=name.lower()).exists():
            return JsonResponse({'message':'This name already exists.'})
        else:    
            Category.objects.create(name=name, description=description)
        return JsonResponse({'message':'Your category was added successfully'})
    return render(request, "todo/add_category.html") 


def serializer_tasks(query):
    return JsonResponse({"object_list":list(query.values('pk', 'title', 'schedule'))})


def serializer_categories(query):
    return JsonResponse({"object_list":list(query.values('pk', 'name', 'description'))})

class TaskListView(ListView):
    model = Task
    def post(self, request, *args, **kwargs):
        print("inside class view")
        queryset = Task.objects.all().order_by('schedule')   
        return serializer_tasks(queryset)


def expired_tasks(request):
    print(request.method)
    print(request.is_ajax())
    if request.method == "POST" and request.is_ajax():
        queryset = Task.objects.filter(schedule__lt = timezone.now())   
        return serializer_tasks(queryset)
    return JsonResponse({})


def unexpired_tasks(request):
    if request.method == "POST" and request.is_ajax():
        queryset = Task.objects.filter(schedule__gte = timezone.now())   
        return serializer_tasks(queryset)
    return JsonResponse({})


def last_tasks(request):
    if request.method == "POST" and request.is_ajax():
        queryset = Task.objects.all().order_by('-time_created')[:3]  
        return serializer_tasks(queryset)
    return JsonResponse({})

class TaskDetailView(DetailView):
    model = Task

class CategoriesListView(ListView):
    model = Category


def empty_categories(request):
    if request.method == "POST" and request.is_ajax():
        queryset = Category.objects.all().annotate(Count('task')).filter(task__count=0)  
        return serializer_categories(queryset)
    return JsonResponse({})


def popular_categories(request):
    if request.method == "POST" and request.is_ajax():
        queryset = Category.objects.annotate(Count('task')).order_by('-task__count')[:3]  
        return serializer_categories(queryset)
    return JsonResponse({})

class CategoryDetailView(DetailView):
    model = Category
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tasks"] = Task.objects.filter(categories=context["category"])
        return context
    
    

reminder/templates/base.html
<!doctype html>
<html lang="en">
  <head>
  	<title>TODO</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"> 
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script> 
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
	{% block head %}{% endblock head %}
  </head>

  <body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<a class="mx-2 navbar-brand" href={% url 'index' %}>TODO Application</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            {% block navbar %}{% endblock navbar %}
          </ul>
        </div>
    </nav>
	<!-- <div class="container-fluid d-flex align-items-stretch"></div> -->

	<div id="content" class="p-4 p-md-5 pt-5">
		{% block content %}{% endblock content %}
	</div>

	{% block script %}{% endblock script %}
  </body>
</html>

reminder/templates/todo/add_category.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}
    <li class="nav-item">
        <a class="nav-link" href={% url 'index' %}>Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href={% url 'admin:index' %}>Admin</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href={% url 'categories' %}>Categories</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href={% url 'tasks' %}>Tasks</a>
    </li>
{% endblock navbar %}

{% block content %}
    <form method="POST" id="category-form">
        {% csrf_token %}
        <h3>Add a new category</h3>
           <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label for="name">Name:</label>      
                        <input id="name" class="form-control" type="text" name="name" maxlength="30" required>
                    </div>
                    <div class="form-group">
                        <label for="description">Description:</label>         
                        <input id="description" class="form-control" type="text" name="description" maxlength="100" required>
                    </div>
                    
                <div class="mx-6 my-2">
                    <button type="submit" class="btn btn-primary w-100">Add</button>
                </div>
                <!-- <div class="col-md-6">
                    
                </div> -->
            </div>
        </form>
{% endblock content %}

{% block script %}
    <script>
        var CSRF_TOKEN = '{{ csrf_token }}';
        var URL = "{% url 'add_category' %}"
    </script>
    <script src={% static '/js/send_category.js' %}></script>
{% endblock script %}

reminder/templates/todo/category_detail.html
{% extends 'base.html' %}
{% block navbar %}
    <li class="nav-item">
        <a class="nav-link" href={% url 'index' %}>Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href={% url 'tasks' %}>Tasks</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href={% url 'admin:index' %}>Admin</a>
    </li>
{% endblock navbar %}
{% block content %}
<h3>Category: {{category.name}}</h3>
<h6 class='mt-3'>Description: {{category.description}}</h6>
<table class="table table-striped mt-4">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Deadline</th>
            <th scope="col">Title</th>
        </tr>
    </thead>
    <tbody>
        {% for task in tasks %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <th >{{task.schedule}}</th>
            <th >{{task.title}}</th>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

reminder/templates/todo/category_list.html
{% extends 'base.html' %}
{% load static %}
{% block navbar %}
    <li class="nav-item">
        <a class="nav-link" href={% url 'index' %}>Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href={% url 'tasks' %}>Tasks</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href={% url 'admin:index' %}>Admin</a>
    </li>
{% endblock navbar %}
{% block content %}
    <h3>Categories</h3>
    <div class="row">
        <div class="col">
            <a href={% url 'empty_categories'%} class="button btn btn-info" >Empty Categories</a>
        </div>
        <div class="col">
            <a href={% url 'popular_categories'%} class="button btn btn-info">Popular Categories</a>
        </div>
    </div>

    <div class="list-group mt-4">
        {% for cat in object_list %}
            <a href="{% url 'category_detail' cat.pk %}" class="list-group-item list-group-item-action">{{cat.name}}</a>
        {% endfor %}
    </div>
{% endblock content %}
{% block script %}
    <script>
        var CSRF_TOKEN = '{{ csrf_token }}';
    </script>
    <script src={% static 'js/category_list.js' %}></script>
{% endblock script %}

reminder/templates/todo/index.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}
    <li class="nav-item">
        <a class="nav-link" href={% url 'admin:index' %}>Admin</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href={% url 'categories' %}>Categories</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href={% url 'tasks' %}>Tasks</a>
    </li>
{% endblock navbar %}

{% block content %}
    <form method="POST" id="task-form">
        {% csrf_token %}
        <h3>Add a new task</h3>
           <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label for="title">Title:</label>      
                        <input id="title" class="form-control" type="text" name="title" maxlength="30" required>
                    </div>
                    <div class="form-group">
                        <label for="description">Description:</label>         
                        <textarea name="description" id="description" cols="40" rows="4" class="form-control" required></textarea> 
                    </div>
                    <div class="form-group">
                        <label class="required" for="id_priority">Priority:</label>
                        <select name="priority" required class="form-control">
                            <option value="" selected="">---------</option>
                            <option value="3">Low</option>
                            <option value="2">Medium</option>
                            <option value="1">High</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <p class="group-label mb-1">Categories:</p>
                        {% for category in categories %}
                            <input class="ms-4" name="categories" type="checkbox" value="{{category.name}}"/>
                            <label class="inline">{{category.name}}</label>
                        {% endfor %} 
                        <label class="ms-4"><a class="btn btn-primary" href={% url 'add_category' %}>other</a></label>
                    </div> 
                    
                    
                    <div class="form-group">
                        <label for="title">Schedule:</label>      
                        <input id="schedule" class="form-control" type="datetime-local" name="schedule" required>
                    </div>
                </div>
                <div class="mx-6 my-2">
                    <button type="submit" class="btn btn-primary w-100">Add</button>
                </div>
                <!-- <div class="col-md-6">
                    
                </div> -->
            </div>
        </form>
{% endblock content %}

{% block script %}
    <script>
        var CSRF_TOKEN = '{{ csrf_token }}';
        var URL = "{% url 'index' %}"
    </script>
    <script src={% static '/js/index.js' %}></script>
{% endblock script %}

reminder/templates/todo/task_detail.html
{% extends 'base.html' %}
{% block head %}
    <script src="https://kit.fontawesome.com/59a3658ff3.js" crossorigin="anonymous"></script>
{% endblock head %}
{% block navbar %}
    <li class="nav-item">
        <a class="nav-link" href={% url 'index' %}>Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href={% url 'admin:index' %}>Admin</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href={% url 'categories' %}>Categories</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href={% url 'tasks' %}>Tasks</a>
    </li>
{% endblock navbar %}
{% block content %}

<div class="container">
    <div class="col-md-12 col-12 col-sm-12">
        <div class="card">
            <div class="card-header">
                <h4>Task Details</h4>
            </div>
            
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <tbody>
                            <tr>
                                <th class="text-center">
                                </th>
                                <th>Task Name</th>
                                <th>Description</th>
                                <th>Deadline</th>
                                <th>Category</th>
                                <th class="text-center">Priority</th>
                            </tr>
                            <tr>
                                <td class="p-0 text-center align-middle">
                                    <div class="custom-checkbox custom-control"> 
                                        <input type="checkbox" data-checkboxes="mygroup" class="custom-control-input" id="checkbox-1" wtx-context="238690F1-7C91-4A49-80DB-2B4BCDD828DE"> 
                                        <label for="checkbox-1" class="custom-control-label">&nbsp;</label>
                                    </div>
                                </td>
                                <td>{{task.title}}</td>
                                <td>{{task.description}}</td>
                                <td>{{task.schedule}}</td>
                                <td class="align-middle">{{task.categories.all|join:", "}}</td>
                                <td class="text-center align-middle">
                                    {% if task.priority != 1 %}
                                        {% if task.priority == 2 %}
                                            <span style="color: Orange;">
                                                <i class="fas fa-circle"></i>
                                            </span>
                                        {% else %}
                                            <span style=" color: Yellow;">
                                                <i class="fas fa-circle"></i>
                                            </span>
                                        {% endif %}
                                    {% else %}
                                        <span style="color: Red;">
                                            <i class="fas fa-circle"></i>
                                        </span>
                                    {% endif %}
    
                                </td>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

reminder/templates/todo/task_list.html
{% extends 'base.html' %}
{% load static %}
{% block navbar %}
    <li class="nav-item">
        <a class="nav-link" href={% url 'index' %}>Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href={% url 'categories' %}>Categories</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href={% url 'admin:index' %}>Admin</a>
    </li>
{% endblock navbar %}

{% block content %}

<div class="row">
    <div class="col">
        <a href={% url 'tasks'%} class="button btn btn-info" >Order by Date</a>
    </div>
    <div class="col">
        <a href={% url 'expired_tasks'%} class="button btn btn-info">Expired Tasks</a>
    </div>
    <div class="col">
        <a href={% url 'unexpired_tasks'%} class="button btn btn-info">Unexpired Tasks</a>
    </div>
    <div class="col">
        <a href={% url 'last_tasks'%} class="button btn btn-info">Last Tasks</a>
    </div>
</div>


<table class="table table-striped mt-4">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Deadline</th>
            <th scope="col">Title</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody id="tasks_list">
        {% for task in object_list %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <th>{{task.schedule | date:"Y-m-d H:i"}}</th>
            <th>{{task.title}}</th>
            <th>
                <a href="{% url 'task_detail' task.pk %}" class="btn btn-info">Detail</a>
            </th>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}
{% block script %}
    <script>
        var CSRF_TOKEN = '{{ csrf_token }}';
    </script>
    <script src={% static 'js/task_list.js' %}></script>
{% endblock script %}